FROM python:3.9

WORKDIR /app

COPY resourcenode.py .
COPY requirements.txt ./requirements.txt

RUN pip install --no-cache-dir -r requirements.txt
RUN pip install flask

CMD ["python", "resourcenode.py"]
