version: '3.8'

services:
  resourcenode:
    build:
      context: ./p2l
      dockerfile: Dockerfile.resourcenode
    ports:
      - "5000:5000"
    networks:
      - Semester-Project-distributed-network-2
    healthcheck:
      test: ["CMD", "curl", "-f", "http://resourcenode:5000/health"]
      interval: 10s
      retries: 5
      timeout: 5s

  servernode1:
    build:
      context: ./p2l
      dockerfile: Dockerfile.servernode
    depends_on:
      resourcenode:
        condition: service_healthy
    networks:
      - Semester-Project-distributed-network-2

  servernode2:
    build:
      context: ./p2l
      dockerfile: Dockerfile.servernode
    depends_on:
      resourcenode:
        condition: service_healthy
    networks:
      - Semester-Project-distributed-network-2

  servernode3:
    build:
      context: ./p2l
      dockerfile: Dockerfile.servernode
    depends_on:
      resourcenode:
        condition: service_healthy
    networks:
      - Semester-Project-distributed-network-2

  servernode4:
    build:
      context: ./p2l
      dockerfile: Dockerfile.servernode
    depends_on:
      resourcenode:
        condition: service_healthy
    networks:
      - Semester-Project-distributed-network-2

  frontend:
    build: ./p2l/frontEnd
    ports:
      - "8080:80"  # Map port 80 of the frontend container to port 5000 of the host
    networks:
      - Semester-Project-distributed-network-2

networks:
  Semester-Project-distributed-network-2:
    driver: bridge
